Refactored Text SVG
varabyte/kobweb pull request #323
Opened 2023-09-22 17:52 UTC by binayshaw7777

This PR completely resolves: #307 
This PR is also a follow-up of #315 #321 

Attributes Covered in Text SVG:
- [x] x (Number, CSSLengthOrPercentageValue)
- [x] y (Number, CSSLengthOrPercentageValue)
- [x] dx (Number, CSSLengthOrPercentageValue)
- [x] dy (Number, CSSLengthOrPercentageValue)
- [x] rotate (vararg Number)
- [x] lengthAdjust (Enum - SvgTextLengthAdjust)
- [x] letterSpacing ((Number, CSSLengthOrPercentageValue)
- [x] wordSpacing (Number, CSSLengthOrPercentageValue)
- [x] textDecoration (TextDecorationLine)
- [x] textLength (Number, CSSLengthOrPercentageValue)
- [x] fontStyle (FontStyle)
- [x] fontSize (Number, CSSLengthOrPercentageValue, FontSize)
- [x] fontWeight (Number, FontWeight)

This also includes some implemented attributes like:
- [x] stroke (CSSColorValue)
- [x] fill (CSSColorValue, Color, Gradient, String)

2023-09-22 22:43 UTC, bitspittle requested changes
Looks great Binay! Essentially approved, just two minor tweaks first.

2023-09-22 22:43 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/dom/Svg.kt
> +    fun fill(value: String) {this.attr("fill", value) }
Let's not provide "fill" which takes a string value. I'm already spending regretted time removing those I added for `Modifier` :) See also: https://github.com/varabyte/kobweb/issues/173

It's true that this will prevent some valid options, but hopefully we can identify them soon and add a typed API for them (probably a version of `fill` that takes an `SVGFill` enum value?).

In the meanwhile, a user can always use `attr("fill", "...")` for the cases we don't support yet.

2023-09-22 22:43 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/dom/Svg.kt
> +    fun rotate(vararg angleDegree: Number) {
Nit: I gave you a bad name example yesterday, sorry about that! `vararg` parameters should be plural, so here, well, `angleDegrees` isn't quite right, and `anglesDegree` isn't quite right...

I'd say let's just change this to `angles` for simplicity.

P.S. I looked at the [`sin`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/sin.html) method for comparison, which there is in radians, but they don't put "radians" in the parameter, so we can probably drop "degrees" here.

2023-09-23 02:17 UTC, binayshaw7777 commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/dom/Svg.kt
> +    fun fill(value: String) {this.attr("fill", value) }
That makes sense to me, removed the overloaded method.

2023-09-23 02:19 UTC, binayshaw7777 commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/dom/Svg.kt
> +    fun rotate(vararg angleDegree: Number) {
I understand your point. Naming convention is sure not an easy task 😅

2023-09-23 03:14 UTC, bitspittle approved these changes

2023-09-24 23:17 UTC, merged