Switch to using KSP for code processing
varabyte/kobweb pull request #325
Opened 2023-09-24 06:34 UTC by DennisTsar

2023-09-25 16:35 UTC, bitspittle requested changes

2023-09-25 16:35 UTC, bitspittle commented on gradle/libs.versions.toml
> +ksp = "1.9.10-1.0.13"
Nit: ksp should be sorted, here and below

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/core/src/main/kotlin/com/varabyte/kobweb/gradle/core/project/frontend/FrontendData.kt
> +//fun FrontendData.assertValid() {
Does this get deleted later?

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/core/build.gradle.kts
> +    api("com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:${libs.versions.ksp.get()}")
I believe you can do something like `libs.ksp.get()` or something like that, so while things are still verbose, at least it doesn't have to be hardcoded?

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/backend/BackendProcessor.kt
> +            // TODO: we're currently resolving due to import alias -- same as in other places
What is the TODO saying we need to do here?

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/backend/BackendProcessor.kt
> +            Dependencies(true), // TODO
What is the TODO saying we need to do here?

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/common/PackageMappingProcessing.kt
> +                    // e.g. `a.b.pkg` -> `"{pkg}"`
Nit: I had a bit of trouble reading this. I might suggest: 

"{}" under `a.b.pkg` resolves to "{pkg}"

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/common/RouteProcessing.kt
> +// returns route
This comment should probably be expanded. Could be fairly simple:

```
/**
 * Process all incoming information to produce a final route.
 *
 * This is useful, for example, to determine the route for a method annotated
 * with `@Page`
 *
 * For example, a method annotated with `@Page` in a file named `Example.kt`
 * and in the package `pages.a.b.c` will generate a route `/a/b/c/example`.
 *
 * This method also has logic to handle dynamic route cases.
 */
```

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/frontend/FrontendProcessor.kt
> +package com.varabyte.kobweb.ksp.frontend
FILE: No action required, just want to say this looks wayyyyy cleaner than my old garbage code.

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/src/main/kotlin/com/varabyte/kobweb/ksp/KobwebProcessorProvider.kt
> +            else -> { // TODo: what to do about this? make predefined EmptySymbolProcessor?
Does this need a TODO? Seems like you're handling it well, and if something goes wrong later, someone will file a bug and we can prioritize fixing it later?

2023-09-25 16:35 UTC, bitspittle commented on gradle-plugins/ksp-processor/build.gradle.kts
> +val DESCRIPTION = "KSP processor for Kobweb" // TODO
What needs to be TODO'd?

2023-09-25 16:45 UTC, bitspittle commented on build.gradle.kts
> +    `kotlin-dsl` apply false
There is nothing wrong with this line. This is just a test. Repeat, this is only a test.

2023-09-25 17:44 UTC, bitspittle requested changes
Don't let the comments distract from the fact that this overall change is awesome. Overall it feels like the codebase is being left in much better shape than before.

I think my only real concern right now is the kspBackendFile method API and the TODO naming in processor-common's build.gradle.kts. I don't think there was anything else I noticed that I'd consider blocking.

2023-09-25 17:44 UTC, bitspittle commented on tools/processor-common/src/main/kotlin/com/varabyte/kobweb/project/frontend/FrontendData.kt
> +fun Iterable<FrontendData>.merge(throwError: (String) -> Unit): FrontendData {
Optional: Maybe it doesn't matter because this method is only used by us, but I might add some docs here about when an error gets thrown: "An error will get thrown if the merged result generates any invalid conditions, like conflicting routes"

(NOTE: However we resolve this, it should be done for BackendData.kt as well)

2023-09-25 17:44 UTC, bitspittle commented on tools/gradle-plugins/application/src/main/kotlin/com/varabyte/kobweb/gradle/application/KobwebApplicationPlugin.kt
> +        // TODO: below we add kobweb sources to ht generatedByKsp... source sets. This is done to prevent KSP from
Nit: "ht"?

2023-09-25 17:44 UTC, bitspittle commented on tools/gradle-plugins/core/src/main/kotlin/com/varabyte/kobweb/gradle/core/extensions/FileGeneratingBlock.kt
> +interface FileGeneratingBlock : ExtensionAware {
Optional: Should we add docs? This interface is very simple, so maybe it's fine as is, but is there anything more we can say about this? What was the value of creating this interface vs. just adding `genDir` properties to each implementing extension?

Note from future Dave: I saw the FileGeneratingBlock used as a generic type in KobwebBlock. So I'm thinking:

```
An interface used for tagging Gradle extensions which are responsible for generating a bunch of files as a result.

Once tagged, we can aggregate all of them, making it easy to query / collect all their outputs together in a way that's very friendly to how Gradle works.
```

2023-09-25 17:44 UTC, bitspittle commented on tools/gradle-plugins/core/src/main/kotlin/com/varabyte/kobweb/gradle/core/util/ProjectExtensions.kt
> -fun Project.getSourceRoots(platform: TargetPlatform<*>): Sequence<File> {
FILE: No action required, just wanted to say thanks for standardizing this and cleaning it up.

2023-09-25 17:44 UTC, bitspittle commented on tools/gradle-plugins/extensions/markdown/src/main/kotlin/com/varabyte/kobwebx/gradle/markdown/MarkdownConfig.kt
> +abstract class MarkdownConfig(baseGenDir: Provider<String>) : FileGeneratingBlock {
Question: This has nothing to do with your changes. I'm just wondering if you think I should rename "MarkdownConfig" to "MarkdownBlock". I *think* this name (MarkdownConfig) came from before I started using a "Block" convention.

If I do this, I'll do it after your changes go in.

2023-09-25 17:44 UTC, bitspittle commented on tools/ksp/project-processors/src/main/kotlin/com/varabyte/kobweb/ksp/common/RouteProcessing.kt
> +// returns route
I think a already left a comment about changing this in an underlying commit, with some example text, but GitHub / IJ didn't seem to carry it here. So just leaving a note to make sure that this gets fixed, but apologies if this ends up being a dupe.

2023-09-25 17:44 UTC, bitspittle commented on tools/processor-common/build.gradle.kts
> +// TODO: strings + filter?
Whatever this is, we should probably figure this out now :) Reach out to me and let me know what you need.

2023-09-25 17:44 UTC, bitspittle commented on tools/processor-common/build.gradle.kts
> +    artifactId.set("process-common")  // TODO
processor-common

2023-09-25 17:44 UTC, bitspittle commented on tools/processor-common/build.gradle.kts
> +    description.set("") // TODO
"Common code shared between KSP and Gradle code responsible for processing a user's Kobweb project." ?

2023-09-25 17:44 UTC, bitspittle commented on tools/ksp/project-processors/build.gradle.kts
> +    artifactId.set("kobweb-project-processors")
Just thinking out loud: Should we call it "kobweb-ksp-project-processors"? Or something else that emphasizes "ksp" in the name? (I'm OK with this name as well too. Does kvision have any interesting naming convention?)

2023-09-25 17:44 UTC, bitspittle commented on playground/site/build.gradle.kts
> +    kspProcessorDependency.set("com.varabyte.kobweb:project-processors")
Just curious, how come this is necessary here?

2023-09-26 04:07 UTC, DennisTsar commented on tools/processor-common/build.gradle.kts
> +    artifactId.set("process-common")  // TODO
I made it `kobweb-processor-common`

2023-09-26 04:08 UTC, DennisTsar commented on tools/processor-common/build.gradle.kts
> +    description.set("") // TODO
Used your suggestion, just removed "user's" - let me know if I should put that back in.

2023-09-26 04:09 UTC, DennisTsar commented on tools/ksp/project-processors/build.gradle.kts
> +    artifactId.set("kobweb-project-processors")
Good idea. Kvision includes "ksp" as well. I added it.

2023-09-26 04:11 UTC, DennisTsar commented on playground/site/build.gradle.kts
> +    kspProcessorDependency.set("com.varabyte.kobweb:project-processors")
By default, the plugin applies `com.varabyte.kobweb:$artifactId:$version`, but because this is a composite build we need `com.varabyte.kobweb:$moduleName`

2023-09-26 16:33 UTC, DennisTsar commented on gradle-plugins/core/src/main/kotlin/com/varabyte/kobweb/gradle/core/processors/FrontendDataProcessor.kt
> +                                    // "{}" represents the name of the file and thus can be used as a unique key only once
Reverted to the old behavior and updated the comment

2023-09-26 16:36 UTC, DennisTsar commented on tools/gradle-plugins/application/src/main/kotlin/com/varabyte/kobweb/gradle/application/ksp/KspFiles.kt
> + * dependencies when it is used as a task input.
Added an example, let me know if you have further suggestions..

2023-09-26 16:37 UTC, DennisTsar commented on tools/gradle-plugins/extensions/markdown/src/main/kotlin/com/varabyte/kobwebx/gradle/markdown/MarkdownConfig.kt
> +abstract class MarkdownConfig(baseGenDir: Provider<String>) : FileGeneratingBlock {
I agree, the rename would make sense for consistency.

2023-09-27 00:03 UTC, bitspittle approved these changes
Optional: I might add a normal comment above VersionUtil pointing out the version value is generated in the project's build.gradle.kts file, but I don't feel too strongly about it.

2023-09-27 02:47 UTC, merged