Implements api events, currently only the dispose event is present, but can be extended in the future
varabyte/kobweb pull request #353
Opened 2023-10-15 17:03 UTC by zypus

Implements the events and dispose callback feature as discusses in #350.

Modifies the server code and the gradle plugin such that the following is now possible:

```kotlin
@InitApi
fun initDatabase(ctx: InitApiContext) {
    val store = // create database

    ctx.events.onDispose { event: DisposeEvent ->
        store.close()
    }

    // setup database
}
```

The InitApiContext gets an additional `events` member. This currently allows to register callbacks for dispose events via the `onDispose` method.

Currently a dispose event is triggered in the following cases:

1. During DEV mode the api.jar is reloaded, will call `dispose(DisposeEvent(reason=DisposeReason.DEV_API_RELOAD))`
2. When the server shuts down normally, will call `dispose(DisposeEvent(reason=DisposeReason.SERVER_SHUTDOWN))`
3. In case the server is shutdown, because the JVM itself is shutdown/killed, will call `dispose(DisposeEvent(reason=DisposeReason.SHUTDOWN_HOOK))` 

 @bitspittle The third option registers a shutdownHook on the engine, maybe that would also be interesting to move some of the current server shutdown code into, because if the server is shutdown unnaturally some of the current shutdown code will not be run.

2023-10-15 21:23 UTC, bitspittle requested changes
Honestly, this is pretty great! You not only got the chance working the way I imagined it should, but you were even very careful to pay attention to the rest of the project (as far as I can tell) when it came to things like parameter order, naming, etc.

Thank you so much!

The change is functionally fine as is, with some very minor comments that should be easy to resolve.

2023-10-15 21:23 UTC, bitspittle commented on backend/kobweb-api/src/main/kotlin/com/varabyte/kobweb/api/event/Events.kt
> +    fun onDispose(callback: (event: DisposeEvent) -> Unit)
This is probably the right place to add a comment about "dispose" not being guaranteed.

I'll write one here not because I want you to take it blindly, but because I used to hate back and forths with code reviewers because they wanted me to write a comment but weren't clear about what they wanted me to say.

Use this as is or adjust it to what you think is best, up to you! I'm going to write it out quickly without thinking too much about what I'm writing:

```
/**
 * Registers a handler which will be triggered when unmanaged server resources should be disposed.
 *
 * A server might initialize some resources that should be removed explicitly if informed that the server
 * is coming to the end of its lifecycle. If so, this callback is the place to handle this.
 *
 * It's important to understand there may be circumstances where this method can't be called, such as
 * a program being forcefully terminated or the machine it is running on losing power. In other words, even
 * though this event is provided, you have to assume there's a chance it won't get called, and you must write
 * your server logic in a way that can recover from these events.
 *
 * That said, this can be very useful at development time, as live reloading may cause a server to restart
 * multiple times in a short period of time.
 */
```

2023-10-15 21:23 UTC, bitspittle commented on backend/kobweb-api/src/main/kotlin/com/varabyte/kobweb/api/dispose/DisposeEvent.kt
> +    DEV_API_RELOAD, SERVER_SHUTDOWN, SHUTDOWN_HOOK
Let's add some short comments to these? Maybe:

- A dispose is requested in response to a dev server being restarted due to a live reload request
- A dispose is requested because the server is about to shut down normally
- A dispose is requested because the JVM running the server was requested to shut down, e.g. in response to Ctrl-C

2023-10-15 22:06 UTC, zypus commented on backend/kobweb-api/src/main/kotlin/com/varabyte/kobweb/api/event/Events.kt
> +    fun onDispose(callback: (event: DisposeEvent) -> Unit)
Thanks a lot, that is indeed very helpful to get an idea what is required. I restructured and reworded your example a bit and expanded on suggesting potential use cases.

2023-10-15 22:11 UTC, zypus commented
Thank you. This change was quite straightforward due to the clear and clean structure you have build. I am glad that I managed to implement it close to what you have envisioned. I am also really happy how clean it ended up for the user side.

I am glad I judged the structure and order of parameters correctly. I am well aware of the importance of names and structure :D.

Happy to contribute, I really like what you are building with kobweb.

2023-10-16 16:42 UTC, bitspittle approved these changes

2023-10-16 16:59 UTC, bitspittle commented
> Happy to contribute, I really like what you are building with kobweb.

Thanks! Really happy to hear that. And thanks for making Kobweb better even with this change! Changes of your quality level are welcome anytime.

If you haven't seen it yet, we have a general roadmap for what we feel is missing for a 1.0 release:
https://docs.google.com/document/d/1n2Jd02yzuxaatpT7gOhEuijzfaSu9UIaQTV2t4EPcPk/preview

That said, we're getting to a point where a lot of what remains in pretty mind numbing stuff. :) You can review that and see if anything in general interests you. 

Since I don't think that many people are using full stack at this point, if you just keep using Kobweb and pushing that feature to its limits, you might come up with a bunch more feature requests that would actually benefit a 1.0 release that I'm totally blind to.

2023-10-16 17:00 UTC, merged

2023-10-16 17:05 UTC, bitspittle commented
Heads up that I just kicked off a new snapshot. It should be ready whenever this comment is at least 20 minutes old.

At that point, you should be able to use your changes if you change your Kobweb version to `0.14.2-SNAPSHOT`

2023-10-17 20:02 UTC, zypus commented
You're welcome and thank you the discussions about the feature. 

I am glad I could add something to the project. I will check out the roadmap and I will probably stumble upon some more features that would be nice to have. Probably the next thing I might have to deal with is authentication related.

2023-10-17 22:58 UTC, bitspittle commented
As we don't have too many backend folks yet, I think if you just do backend work in your project and stay in touch with me if you have ideas, well, that would be great!

Keep in mind auth in a website produced by a framework like Kobweb is tricky, because you download the whole site at once. You can contrast this to using ktor directly, where you could add auth to routes on a case by case basis, because the user has to hit the network each time to change pages.

My notes are a little sloppy here, but you can take a look at #254 to see a few more details of what I was thinking. 

In Kobweb, I suspect auth will be best served by 1) integration on the frontend side and/or 2) an awesome auth library on the backend (plus some manual labor to check auth in each relevant API request)

## frontend


Despite the user downloading the whole site, we could still have logic to redirect to a different page if credentials are not found.

It's possible auth is handled by some `@Auth` annotation that I haven't really thought too deeply about yet.

## backend

With a backend approach, I think you'd let users navigate to any page, but on each page that requires auth, you'd make an API call first to check if they're logged in, and if not, reroute to a login page then. (You can use local storage or session storage to cache a login key).

And then, don't ever return data from any of your protected API routes if the user doesn't pass in identifying keys in the get params or post body.

It's fuzzy in my memory now, but I think I do something like this a bit with `kobweb create examples/chat`

---

Of course, open to hear any other ideas you have! Or if you find any other feature missing from the backend that you think would be interesting to work on.