Add css attribute multi-column
varabyte/kobweb pull request #414
Opened 2024-01-02 18:09 UTC by ellet0

2024-01-03 21:29 UTC, bitspittle requested changes

2024-01-03 21:29 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +        //        val RevertLayer get() = MultiColumn("revert-layer")
I've seen this before from a different commit, so I thought I'd mention that this  commented out `RevertLayer` line shouldn't be included at all. Instead, just have Inherit, Initial, Revert, and Unset be all next to each other.

FYI this is eventually going to get refactored out into a separate interface anyway, so it's going to go away eventually :) But in general, you shouldn't ever submit commented out code EXCEPT in comments that are explaining code examples for clarity (as far as I can think of right now)

2024-01-03 21:29 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +class MultiColumn private constructor(private val value: String) : StylePropertyValue {
I think there may have been some confusion in what I was saying.

I meant the _file_ should be called "MultiColumn.kt", but the name of each class should come from its CSS property.

Here, that means we'll have classes / stylescope methods here for:

```
break-after
break-before
break-inside
column-fill
column-gap
column-span
column-rule-color
column-rule-style
column-rule-width
column-count
column-width
```

I'm not sure each CSS property needs a class (honestly, `column-rule-color`, `style`, and `width` can probably just be functions).

But if you DO need to create a class (for example, https://developer.mozilla.org/en-US/docs/Web/CSS/break-after will need one), then that would be `class BreakAfter`).

2024-01-03 21:29 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +// https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule
Note that "column-rule" is a shorthand property for "column-rule-color", "column-rule-width", and "column-rule-style". So we shouldn't define a `ColumnRule` class.

2024-01-03 21:29 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +fun StyleScope.multiColumn(multiColumn: MultiColumn) {
This method shouldn't exist at all

2024-01-03 21:29 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +fun StyleScope.multiColumn(color: CSSColorValue) {
This should be `StyleScope.columnRuleColor`

This comment applies to the methods below, as well as to the methods defined in MultiColumnModifiers.kt

2024-01-03 21:32 UTC, bitspittle commented on frontend/kobweb-compose/src/jsMain/kotlin/com/varabyte/kobweb/compose/ui/modifiers/MultiColumnModifiers.kt
> +fun Modifier.multiColumn(multiColumn: MultiColumn) = styleModifier {
Please check what "BorderModifiers.kt" is doing, with its introduction of a `BorderScope` class. We'll want to copy that style over here.

2024-01-04 21:16 UTC, ellet0 commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +fun StyleScope.multiColumn(color: CSSColorValue) {
Done

2024-01-04 23:01 UTC, bitspittle requested changes

2024-01-04 23:01 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +fun StyleScope.columnRuleColor(color: CSSColorValue) {
Everything here and down is perfect.

2024-01-05 08:17 UTC, ellet0 commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +fun StyleScope.columnRule(columnRule: ColumnRule) {
So we will not support the global keywords?

2024-01-05 08:41 UTC, ellet0 commented on frontend/kobweb-compose/src/jsMain/kotlin/com/varabyte/kobweb/compose/ui/modifiers/MultiColumnModifiers.kt
> +fun Modifier.columnRule(columnRule: ColumnRule) = styleModifier {
How about now? I think we still do need more changes

2024-01-05 19:06 UTC, bitspittle approved these changes
Approved with super minor requests. Thank you for this PR!

2024-01-05 19:06 UTC, bitspittle commented on frontend/kobweb-compose/src/jsMain/kotlin/com/varabyte/kobweb/compose/ui/modifiers/MultiColumnModifiers.kt
> +class ColumnRuleScope internal constructor(private val styleScope: StyleScope) {
Nit: Space between imports and class. (Actually, can you just run `Code > Reformat Code`?)

2024-01-05 19:06 UTC, bitspittle commented on frontend/kobweb-compose/src/jsMain/kotlin/com/varabyte/kobweb/compose/ui/modifiers/MultiColumnModifiers.kt
> +    fun width(topAndBottom: CSSLengthNumericValue, leftAndRight: CSSLengthNumericValue) =
No action required: I'm actually talking with another dev on Kobweb and in just the last few days we decided that we should be calling this "topBottom" and "leftRight", without the "And".

If you submit this as is, that's fine, I can fix it shortly when we make the change, but if you're going to do the "reformat code" anyway, would you mind renaming this?

2024-01-05 19:06 UTC, bitspittle commented on frontend/compose-html-ext/src/jsMain/kotlin/com/varabyte/kobweb/compose/css/MultiColumn.kt
> +
Optional: What do you think about a comment at the top of the file linking to Mozilla docs, like:

```
package com.varabyte.kobweb.compose.css

// This file contains CSS properties as described here:
// https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_multicol_layout

import org.jetbrains.compose.web.css.*

fun StyleScope.columnRuleColor(color: CSSColorValue) {
```

2024-01-09 04:03 UTC, bitspittle commented
Merged via command line, guess I need to close the PR manually! 
https://github.com/varabyte/kobweb/commit/30e3c34c06cfff789dc445811f90909320847350

2024-01-09 04:03 UTC, closed without merging